"""add model_override to jobs

Revision ID: 0f9594c35427
Revises: 80269ea6e01a
Create Date: 2026-04-04 19:07:44.631108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9594c35427'
down_revision: Union[str, None] = '80269ea6e01a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('model_override', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'model_override')
    # ### end Alembic commands ###
