"""add glossary and refine_mode to jobs

Revision ID: 2bb750402812
Revises: 755179ec335c
Create Date: 2026-03-23 15:00:35.316601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb750402812'
down_revision: Union[str, None] = '755179ec335c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('glossary', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('refine_mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'refine_mode')
    op.drop_column('jobs', 'glossary')
    # ### end Alembic commands ###
