"""add error_detail to jobs

Revision ID: 3decbf6312b0
Revises: 0f9594c35427
Create Date: 2026-04-07 23:14:47.338078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3decbf6312b0'
down_revision: Union[str, None] = '0f9594c35427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('error_detail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'error_detail')
    # ### end Alembic commands ###
