"""add segments_json to jobs

Revision ID: 7a2b5d55730d
Revises: 3decbf6312b0
Create Date: 2026-04-14 00:20:45.851031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2b5d55730d'
down_revision: Union[str, None] = '3decbf6312b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('segments_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'segments_json')
    # ### end Alembic commands ###
