"""add speakers and speaker_map to jobs

Revision ID: 80269ea6e01a
Revises: a0fd54d5fe67
Create Date: 2026-04-04 15:07:53.189705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80269ea6e01a'
down_revision: Union[str, None] = 'a0fd54d5fe67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('speakers', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('speaker_map', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'speaker_map')
    op.drop_column('jobs', 'speakers')
    # ### end Alembic commands ###
